In [1]:
import pandas as pd
import numpy as np
import os
import sys

In [2]:
DATA_DIRECTORY = "/home/teamq-g2-no2/DiabeteDatachain/data/processed"

# 1999-2000

In [3]:
# selected_column = [
#     "RIDAGEYR","RIDRETH1","BMXWAIST","BMXBMI","LBXGLU","LBXGLUSI","LBDSCHSI","LBDHDLSI","LBDLDLSI","LBDTRSI","LBXHGB","LBXHCT",
#     "LBXMCVSI","LBXMC","LBXRDW","LBXPLTSI","LBXMPSI","LBDHBG","LBXTSH","LB2VID"
# ]
# # file paths
# DEMO_PATH = os.path.join(DATA_DIRECTORY, "1999-2000", "Demographics")
# LAB_PATH = os.path.join(DATA_DIRECTORY, "1999-2000", "Laboratory")
# EXAM_PATH = os.path.join(DATA_DIRECTORY, "1999-2000", "Examination")

# DEMO_99    = pd.read_csv(os.path.join(DEMO_PATH, "DEMO.csv"))
# BMX_99      = pd.read_csv(os.path.join(EXAM_PATH, "BMX.csv"))
# LAB10AM_99  = pd.read_csv(os.path.join(LAB_PATH, "LAB10AM.csv"))
# LAB18_99    = pd.read_csv(os.path.join(LAB_PATH, "LAB18.csv"))
# LAB13_99    = pd.read_csv(os.path.join(LAB_PATH, "LAB13.csv"))
# LAB13AM_99  = pd.read_csv(os.path.join(LAB_PATH, "LAB13AM.csv"))
# LAB25_99    = pd.read_csv(os.path.join(LAB_PATH, "LAB25.csv"))
# LAB02_99    = pd.read_csv(os.path.join(LAB_PATH, "LAB02.csv"))
# LAB18T4_99  = pd.read_csv(os.path.join(LAB_PATH, "LAB18T4.csv"))
# VID_2_00_99 = pd.read_csv(os.path.join(LAB_PATH, "VID_2_00.csv"))
# #filter
# DEMO_99 = DEMO_99.loc[:,DEMO_99.columns.isin(selected_column)]
# BMX_99 = BMX_99.loc[:,BMX_99.columns.isin(selected_column)]
# LAB10AM_99 = LAB10AM_99.loc[:,LAB10AM_99.columns.isin(selected_column)]
# LAB18_99 = LAB18_99.loc[:,LAB18_99.columns.isin(selected_column)]
# LAB13_99 = LAB13_99.loc[:,LAB13_99.columns.isin(selected_column)]
# LAB13AM_99 = LAB13AM_99.loc[:,LAB13AM_99.columns.isin(selected_column)]
# LAB25_99 = LAB25_99.loc[:,LAB25_99.columns.isin(selected_column)]
# LAB02_99 = LAB02_99.loc[:,LAB02_99.columns.isin(selected_column)]
# LAB18T4_99 = LAB18T4_99.loc[:,LAB18T4_99.columns.isin(selected_column)]
# VID_2_00_99 = VID_2_00_99.loc[:,VID_2_00_99.columns.isin(selected_column)]

# # Merge all dataframes
# merged_df_99 = pd.merge(DEMO_99, BMX_99, on="SEQN", how="inner")
# merged_df_99 = pd.merge(merged_df_99, LAB10AM_99, on="SEQN", how="inner")
# merged_df_99 = pd.merge(merged_df_99, LAB18_99, on="SEQN", how="inner")
# merged_df_99 = pd.merge(merged_df_99, LAB13_99, on="SEQN", how="inner")
# merged_df_99 = pd.merge(merged_df_99, LAB13AM_99, on="SEQN", how="inner")
# merged_df_99 = pd.merge(merged_df_99, LAB25_99, on="SEQN", how="inner")
# merged_df_99 = pd.merge(merged_df_99, LAB02_99, on="SEQN", how="inner")
# merged_df_99 = pd.merge(merged_df_99, LAB18T4_99, on="SEQN", how="inner")
# merged_df_99 = pd.merge(merged_df_99, VID_2_00_99, on="SEQN", how="inner")

# 2001-2002

In [4]:
selected_columns_B = [
    "SEQN","RIAGENDR","RIDAGEYR", "RIDRETH1",         # DEMO_B
    "BMXWAIST", "BMXBMI",                   # BMX_B
    "LBXGLU", "LBXGLUSI",                   # L10AM_B
    "LBDSCHSI",                             # L40_B
    "LBDHDLSI",                             # L13_B
    "LBDLDLSI",        
    "LBDTRSI",                           # L13AM_B
    "LBXHGB", "LBXHCT", "LBXMCVSI", "LBXMC", "LBXRDW", "LBXPLTSI", "LBXMPSI",  # L25_B
    "LBDHBG",                               # L02_B
    "LBXTSH",                               # L40T4_B
    "LBDVIDMS",                                # VID_2_B
    "LBXGH"
]
DEMO_PATH = os.path.join(DATA_DIRECTORY, "2001-2002", "Demographics")
LAB_PATH = os.path.join(DATA_DIRECTORY, "2001-2002", "Laboratory")
EXAM_PATH = os.path.join(DATA_DIRECTORY, "2001-2002", "Examination")


DEMO_B     = pd.read_csv(os.path.join(DEMO_PATH, "DEMO_B.csv"))
BMX_B      = pd.read_csv(os.path.join(EXAM_PATH, "BMX_B.csv"))
L10AM_B    = pd.read_csv(os.path.join(LAB_PATH, "L10AM_B.csv"))
L10_B    = pd.read_csv(os.path.join(LAB_PATH, "L10_B.csv"))
L40_B      = pd.read_csv(os.path.join(LAB_PATH, "L40_B.csv"))
L13_B      = pd.read_csv(os.path.join(LAB_PATH, "L13_B.csv"))
L13AM_B    = pd.read_csv(os.path.join(LAB_PATH, "L13AM_B.csv"))
L25_B      = pd.read_csv(os.path.join(LAB_PATH, "L25_B.csv"))
L02_B      = pd.read_csv(os.path.join(LAB_PATH, "L02_B.csv"))
# L40T4_B    = pd.read_csv(os.path.join(LAB_PATH, "L40T4_B.csv"))
VID_2_B    = pd.read_csv(os.path.join(LAB_PATH, "VID_B.csv"))

DEMO_B     = DEMO_B.loc[:, DEMO_B.columns.isin(selected_columns_B)]
BMX_B      = BMX_B.loc[:, BMX_B.columns.isin(selected_columns_B)]
L10AM_B    = L10AM_B.loc[:, L10AM_B.columns.isin(selected_columns_B)]
L40_B      = L40_B.loc[:, L40_B.columns.isin(selected_columns_B)]
L13_B      = L13_B.loc[:, L13_B.columns.isin(selected_columns_B)]
L13AM_B    = L13AM_B.loc[:, L13AM_B.columns.isin(selected_columns_B)]
L25_B      = L25_B.loc[:, L25_B.columns.isin(selected_columns_B)]
L02_B      = L02_B.loc[:, L02_B.columns.isin(selected_columns_B)]
L10_B    = L10_B.loc[:, L10_B.columns.isin(selected_columns_B)]
# L40T4_B    = L40T4_B.loc[:, L40T4_B.columns.isin(selected_columns_B)]
VID_2_B    = VID_2_B.loc[:, VID_2_B.columns.isin(selected_columns_B)]

# Start with DEMO_B
merged_df_B = DEMO_B

# Merge one by one on SEQN
merged_df_B = pd.merge(merged_df_B, BMX_B, on="SEQN", how="inner")
merged_df_B = pd.merge(merged_df_B, L10AM_B, on="SEQN", how="inner")
merged_df_B = pd.merge(merged_df_B, L40_B, on="SEQN", how="inner")
merged_df_B = pd.merge(merged_df_B, L13_B, on="SEQN", how="inner")
merged_df_B = pd.merge(merged_df_B, L13AM_B, on="SEQN", how="inner")
merged_df_B = pd.merge(merged_df_B, L25_B, on="SEQN", how="inner")
merged_df_B = pd.merge(merged_df_B, L02_B, on="SEQN", how="inner")
merged_df_B = pd.merge(merged_df_B, L10_B, on="SEQN", how="inner")
# merged_df_B = pd.merge(merged_df_B, L40T4_B, on="SEQN", how="inner")
merged_df_B = pd.merge(merged_df_B, VID_2_B, on="SEQN", how="inner")
merged_df_B.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3666 entries, 0 to 3665
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      3666 non-null   float64
 1   RIAGENDR  3666 non-null   float64
 2   RIDAGEYR  3666 non-null   float64
 3   RIDRETH1  3666 non-null   float64
 4   BMXBMI    3493 non-null   float64
 5   BMXWAIST  3515 non-null   float64
 6   LBXGLU    3441 non-null   float64
 7   LBXGLUSI  3441 non-null   float64
 8   LBDSCHSI  3392 non-null   float64
 9   LBDHDLSI  3382 non-null   float64
 10  LBDTRSI   3382 non-null   float64
 11  LBDLDLSI  3038 non-null   float64
 12  LBXHGB    3460 non-null   float64
 13  LBXHCT    3460 non-null   float64
 14  LBXMCVSI  3460 non-null   float64
 15  LBXMC     3460 non-null   float64
 16  LBXRDW    3460 non-null   float64
 17  LBXPLTSI  3460 non-null   float64
 18  LBXMPSI   3460 non-null   float64
 19  LBDHBG    3418 non-null   float64
 20  LBXGH     3457 non-null   float64
 21  LBDVIDMS  3344 non-null   float64
dtypes: float64(22)
memory usage: 630.2 KB

# 2003-2004

In [5]:
selected_columns_C = [
    "SEQN","RIAGENDR", "RIDAGEYR", "RIDRETH1",         # DEMO_C
    "BMXWAIST", "BMXBMI",                   # BMX_C
    "LBXGLU",                               # L10AM_C
    "LBDSUASI", "LBDSCHSI", "LBXTSH", 
     # L40_C
    "LBDHDDSI",                             # L13_C
    "LBDLDLSI",
    "LBDTRSI",                             # L13AM_C
    "LBXHGB", "LBXHCT", "LBXMCVSI", "LBXMC", "LBXRDW", "LBXPLTSI", "LBXMPSI",  # L25_C
    "LBDHBG",                               # L02_C
    "LBDVIDMS",                                # L06VID_C
    "LBXGH"
]
DEMO_PATH = os.path.join(DATA_DIRECTORY, "2003-2004", "Demographics")
LAB_PATH = os.path.join(DATA_DIRECTORY, "2003-2004", "Laboratory")
EXAM_PATH = os.path.join(DATA_DIRECTORY, "2003-2004", "Examination")

DEMO_C     = pd.read_csv(os.path.join(DEMO_PATH, "DEMO_C.csv"))
BMX_C      = pd.read_csv(os.path.join(EXAM_PATH, "BMX_C.csv"))
L10AM_C    = pd.read_csv(os.path.join(LAB_PATH, "L10AM_C.csv"))
L40_C      = pd.read_csv(os.path.join(LAB_PATH, "L40_C.csv"))
L13_C      = pd.read_csv(os.path.join(LAB_PATH, "L13_C.csv"))
L10_C      = pd.read_csv(os.path.join(LAB_PATH, "L10_C.csv"))

L13AM_C    = pd.read_csv(os.path.join(LAB_PATH, "L13AM_C.csv"))
L25_C      = pd.read_csv(os.path.join(LAB_PATH, "L25_C.csv"))
L02_C      = pd.read_csv(os.path.join(LAB_PATH, "L02_C.csv"))
L06VID_C   = pd.read_csv(os.path.join(LAB_PATH, "VID_C.csv"))

DEMO_C     = DEMO_C.loc[:, DEMO_C.columns.isin(selected_columns_C)]
BMX_C      = BMX_C.loc[:, BMX_C.columns.isin(selected_columns_C)]
L10AM_C    = L10AM_C.loc[:, L10AM_C.columns.isin(selected_columns_C)]
L40_C      = L40_C.loc[:, L40_C.columns.isin(selected_columns_C)]
L13_C      = L13_C.loc[:, L13_C.columns.isin(selected_columns_C)]
L10_C      = L10_C.loc[:, L10_C.columns.isin(selected_columns_C)]

L13AM_C    = L13AM_C.loc[:, L13AM_C.columns.isin(selected_columns_C)]
L25_C      = L25_C.loc[:, L25_C.columns.isin(selected_columns_C)]
L02_C      = L02_C.loc[:, L02_C.columns.isin(selected_columns_C)]
L06VID_C   = L06VID_C.loc[:, L06VID_C.columns.isin(selected_columns_C)]

merged_df_C = DEMO_C
merged_df_C = pd.merge(merged_df_C, BMX_C, on="SEQN", how="inner")
merged_df_C = pd.merge(merged_df_C, L10AM_C, on="SEQN", how="inner")
merged_df_C = pd.merge(merged_df_C, L40_C, on="SEQN", how="inner")
merged_df_C = pd.merge(merged_df_C, L13_C, on="SEQN", how="inner")
merged_df_C = pd.merge(merged_df_C, L13AM_C, on="SEQN", how="inner")
merged_df_C = pd.merge(merged_df_C, L25_C, on="SEQN", how="inner")
merged_df_C = pd.merge(merged_df_C, L02_C, on="SEQN", how="inner")
merged_df_C = pd.merge(merged_df_C, L10_C, on="SEQN", how="inner")
merged_df_C = pd.merge(merged_df_C, L06VID_C, on="SEQN", how="inner")
merged_df_C.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3356 entries, 0 to 3355
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      3356 non-null   float64
 1   RIAGENDR  3356 non-null   float64
 2   RIDAGEYR  3356 non-null   float64
 3   RIDRETH1  3356 non-null   float64
 4   BMXBMI    3308 non-null   float64
 5   BMXWAIST  3205 non-null   float64
 6   LBXGLU    3169 non-null   float64
 7   LBDSCHSI  3138 non-null   float64
 8   LBDSUASI  3138 non-null   float64
 9   LBDHDDSI  3148 non-null   float64
 10  LBDTRSI   3141 non-null   float64
 11  LBDLDLSI  3079 non-null   float64
 12  LBXHGB    3199 non-null   float64
 13  LBXHCT    3199 non-null   float64
 14  LBXMCVSI  3199 non-null   float64
 15  LBXMC     3199 non-null   float64
 16  LBXRDW    3199 non-null   float64
 17  LBXPLTSI  3199 non-null   float64
 18  LBXMPSI   3199 non-null   float64
 19  LBDHBG    3159 non-null   float64
 20  LBXGH     3191 non-null   float64
 21  LBDVIDMS  3165 non-null   float64
dtypes: float64(22)
memory usage: 576.9 KB

# 2005-2006

In [6]:
selected_columns = ["SEQN","RIAGENDR", "RIDAGEYR", "RIDRETH1", "BMXWAIST", "BMXBMI", "LBXGLU", "LBDSUASI", "LBDSCHSI",
"LBDHDDSI","LBDLDLSI","LBDSTRSI","LBXHGB", "LBXHCT","LBXMCVSI","LBXMC","LBXRDW","LBXPLTSI", "LBXMPSI", "LBDHBG", "LBDTSH1S", "LBDVIDMS","LBXGH"]

# file paths
DEMO_PATH = os.path.join(DATA_DIRECTORY, "2005-2006", "Demographics")
LAB_PATH = os.path.join(DATA_DIRECTORY, "2005-2006", "Laboratory")
EXAM_PATH = os.path.join(DATA_DIRECTORY, "2005-2006", "Examination")

# Read in the data
DEMO_D     = pd.read_csv(os.path.join(DEMO_PATH, "DEMO_D.csv"))
BMX_D      = pd.read_csv(os.path.join(EXAM_PATH, "BMX_D.csv"))
GLU_D      = pd.read_csv(os.path.join(LAB_PATH, "GLU_D.csv"))
BIOPRO_D   = pd.read_csv(os.path.join(LAB_PATH, "BIOPRO_D.csv"))
HDL_D      = pd.read_csv(os.path.join(LAB_PATH, "HDL_D.csv"))
TRIGLY_D   = pd.read_csv(os.path.join(LAB_PATH, "TRIGLY_D.csv"))
CBC_D      = pd.read_csv(os.path.join(LAB_PATH, "CBC_D.csv"))
HEPBD_D    = pd.read_csv(os.path.join(LAB_PATH, "HEPBD_D.csv"))
GHB_D     = pd.read_csv(os.path.join(LAB_PATH, "GHB_D.csv"))
# THYROD_D   = pd.read_csv(os.path.join(LAB_PATH, "THYROD_D.csv"))
VID_D      = pd.read_csv(os.path.join(LAB_PATH, "VID_D.csv"))

# Get columns in the files
DEMO_D = DEMO_D.loc[:, DEMO_D.columns.isin(selected_columns)]
BMX_D = BMX_D.loc[:, BMX_D.columns.isin(selected_columns)]
GLU_D = GLU_D.loc[:, GLU_D.columns.isin(selected_columns)]
BIOPRO_D = BIOPRO_D.loc[:, BIOPRO_D.columns.isin(selected_columns)]
HDL_D = HDL_D.loc[:, HDL_D.columns.isin(selected_columns)]
TRIGLY_D = TRIGLY_D.loc[:, TRIGLY_D.columns.isin(selected_columns)]
CBC_D = CBC_D.loc[:, CBC_D.columns.isin(selected_columns)]
HEPBD_D = HEPBD_D.loc[:, HEPBD_D.columns.isin(selected_columns)]
GHB_D = GHB_D.loc[:, GHB_D.columns.isin(selected_columns)]
# THYROD_D = THYROD_D.loc[:, THYROD_D.columns.isin(selected_columns)]
VID_D = VID_D.loc[:, VID_D.columns.isin(selected_columns)]

# Merge the dataframes
merged_df_D = pd.merge(DEMO_D, BMX_D, on="SEQN", how="inner")
merged_df_D = pd.merge(merged_df_D, GLU_D, on="SEQN", how="inner")
merged_df_D = pd.merge(merged_df_D, BIOPRO_D, on="SEQN", how="inner")
merged_df_D = pd.merge(merged_df_D, HDL_D, on="SEQN", how="inner")
merged_df_D = pd.merge(merged_df_D, TRIGLY_D, on="SEQN", how="inner")
merged_df_D = pd.merge(merged_df_D, CBC_D, on="SEQN", how="inner")
merged_df_D = pd.merge(merged_df_D, HEPBD_D, on="SEQN", how="inner")
merged_df_D = pd.merge(merged_df_D, GHB_D, on="SEQN", how="inner")
# merged_df_D = pd.merge(merged_df_D, THYROD_D, on="SEQN", how="inner")
merged_df_D = pd.merge(merged_df_D, VID_D, on="SEQN", how="inner")
merged_df_D.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3352 entries, 0 to 3351
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      3352 non-null   float64
 1   RIAGENDR  3352 non-null   float64
 2   RIDAGEYR  3352 non-null   float64
 3   RIDRETH1  3352 non-null   float64
 4   BMXBMI    3302 non-null   float64
 5   BMXWAIST  3216 non-null   float64
 6   LBXGLU    3128 non-null   float64
 7   LBDSCHSI  3094 non-null   float64
 8   LBDSTRSI  3093 non-null   float64
 9   LBDSUASI  3095 non-null   float64
 10  LBDHDDSI  3106 non-null   float64
 11  LBDLDLSI  3026 non-null   float64
 12  LBXHGB    3137 non-null   float64
 13  LBXHCT    3137 non-null   float64
 14  LBXMCVSI  3137 non-null   float64
 15  LBXMC     3137 non-null   float64
 16  LBXRDW    3137 non-null   float64
 17  LBXPLTSI  3137 non-null   float64
 18  LBXMPSI   3137 non-null   float64
 19  LBDHBG    3119 non-null   float64
 20  LBXGH     3131 non-null   float64
 21  LBDVIDMS  3121 non-null   float64
dtypes: float64(22)
memory usage: 576.3 KB

# 2007-2008

In [7]:
selected_columns = ["SEQN","RIAGENDR", "RIDAGEYR", "RIDRETH1", "BMXWAIST", "BMXBMI", "LBXGLU", "LBDSUASI", "LBDSCHSI",
"LBDHDDSI","LBDLDLSI","LBDSTRSI","LBXHGB", "LBXHCT","LBXMCVSI","LBXMC","LBXRDW","LBXPLTSI", "LBXMPSI", "LBDHBG", "LBDTSH1S", "LBXVIDMS","LBXGH"]

#file paths
DEMO_PATH = os.path.join(DATA_DIRECTORY, "2007-2008", "Demographics")
LAB_PATH = os.path.join(DATA_DIRECTORY, "2007-2008", "Laboratory")
EXAM_PATH = os.path.join(DATA_DIRECTORY, "2007-2008", "Examination")

#read in the data
DEMO_E     = pd.read_csv(os.path.join(DEMO_PATH, "DEMO_E.csv"))
BMX_E      = pd.read_csv(os.path.join(EXAM_PATH, "BMX_E.csv"))
GLU_E      = pd.read_csv(os.path.join(LAB_PATH, "GLU_E.csv"))
BIOPRO_E   = pd.read_csv(os.path.join(LAB_PATH, "BIOPRO_E.csv"))
HDL_E      = pd.read_csv(os.path.join(LAB_PATH, "HDL_E.csv"))
TRIGLY_E   = pd.read_csv(os.path.join(LAB_PATH, "TRIGLY_E.csv"))
CBC_E      = pd.read_csv(os.path.join(LAB_PATH, "CBC_E.csv"))
HEPBD_E    = pd.read_csv(os.path.join(LAB_PATH, "HEPBD_E.csv"))
GHB_E     = pd.read_csv(os.path.join(LAB_PATH, "GHB_E.csv"))
# THYROD_E   = pd.read_csv(os.path.join(LAB_PATH, "THYROD_E.csv"))
VID_E      = pd.read_csv(os.path.join(LAB_PATH, "VID_E.csv"))

#get columns in the files
DEMO_E = DEMO_E.loc[:, DEMO_E.columns.isin(selected_columns)]
BMX_E = BMX_E.loc[:, BMX_E.columns.isin(selected_columns)]
GLU_E = GLU_E.loc[:, GLU_E.columns.isin(selected_columns)]
BIOPRO_E = BIOPRO_E.loc[:, BIOPRO_E.columns.isin(selected_columns)]
HDL_E = HDL_E.loc[:, HDL_E.columns.isin(selected_columns)]
TRIGLY_E = TRIGLY_E.loc[:, TRIGLY_E.columns.isin(selected_columns)]
CBC_E = CBC_E.loc[:, CBC_E.columns.isin(selected_columns)]
HEPBD_E = HEPBD_E.loc[:, HEPBD_E.columns.isin(selected_columns)]
# THYROD_E = THYROD_E.loc[:, THYROD_E.columns.isin(selected_columns)]
GHB_E = GHB_E.loc[:, GHB_E.columns.isin(selected_columns)]
VID_E = VID_E.loc[:, VID_E.columns.isin(selected_columns)]

#merge the dataframes
merged_df_E = pd.merge(DEMO_E, BMX_E, on="SEQN", how="inner")
merged_df_E = pd.merge(merged_df_E, GLU_E, on="SEQN", how="inner")
merged_df_E = pd.merge(merged_df_E, BIOPRO_E, on="SEQN", how="inner")
merged_df_E = pd.merge(merged_df_E, HDL_E, on="SEQN", how="inner")
merged_df_E = pd.merge(merged_df_E, TRIGLY_E, on="SEQN", how="inner")
merged_df_E = pd.merge(merged_df_E, CBC_E, on="SEQN", how="inner")
merged_df_E = pd.merge(merged_df_E, HEPBD_E, on="SEQN", how="inner")
merged_df_E = pd.merge(merged_df_E, GHB_E, on="SEQN", how="inner")
# merged_df_E = pd.merge(merged_df, THYROD_E, on="SEQN", how="inner")
merged_df_E = pd.merge(merged_df_E, VID_E, on="SEQN", how="inner")
merged_df_E.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3315 entries, 0 to 3314
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      3315 non-null   float64
 1   RIAGENDR  3315 non-null   float64
 2   RIDAGEYR  3315 non-null   float64
 3   RIDRETH1  3315 non-null   float64
 4   BMXBMI    3251 non-null   float64
 5   BMXWAIST  3136 non-null   float64
 6   LBXGLU    3110 non-null   float64
 7   LBDSCHSI  3085 non-null   float64
 8   LBDSTRSI  3085 non-null   float64
 9   LBDSUASI  3085 non-null   float64
 10  LBDHDDSI  3102 non-null   float64
 11  LBDLDLSI  3035 non-null   float64
 12  LBXHGB    3112 non-null   float64
 13  LBXHCT    3112 non-null   float64
 14  LBXMCVSI  3112 non-null   float64
 15  LBXMC     3112 non-null   float64
 16  LBXRDW    3112 non-null   float64
 17  LBXPLTSI  3112 non-null   float64
 18  LBXMPSI   3112 non-null   float64
 19  LBDHBG    3111 non-null   float64
 20  LBXGH     3110 non-null   float64
 21  LBXVIDMS  2682 non-null   float64
dtypes: float64(22)
memory usage: 569.9 KB

# 2009-2010

In [8]:
selected_columns = ["SEQN","RIAGENDR", "RIDAGEYR", "RIDRETH1", "BMXWAIST", "BMXBMI", "LBXGLU", "LBDSUASI", "LBDSCHSI",
"LBDHDDSI","LBDLDLSI","LBDSTRSI","LBXHGB", "LBXHCT","LBXMCVSI","LBXMC","LBXRDW","LBXPLTSI", "LBXMPSI", "LBDHBG", "LBDTSH1S", "LBXVIDMS","LBXGH"]

#file paths
DEMO_PATH = os.path.join(DATA_DIRECTORY, "2009-2010", "Demographics")
LAB_PATH = os.path.join(DATA_DIRECTORY, "2009-2010", "Laboratory")
EXAM_PATH = os.path.join(DATA_DIRECTORY, "2009-2010", "Examination")

#read in the data
DEMO_F     = pd.read_csv(os.path.join(DEMO_PATH, "DEMO_F.csv"))
BMX_F      = pd.read_csv(os.path.join(EXAM_PATH, "BMX_F.csv"))
GLU_F      = pd.read_csv(os.path.join(LAB_PATH, "GLU_F.csv"))
BIOPRO_F   = pd.read_csv(os.path.join(LAB_PATH, "BIOPRO_F.csv"))
HDL_F      = pd.read_csv(os.path.join(LAB_PATH, "HDL_F.csv"))
TRIGLY_F   = pd.read_csv(os.path.join(LAB_PATH, "TRIGLY_F.csv"))
CBC_F      = pd.read_csv(os.path.join(LAB_PATH, "CBC_F.csv"))
HEPBD_F    = pd.read_csv(os.path.join(LAB_PATH, "HEPBD_F.csv"))
GHB_F     = pd.read_csv(os.path.join(LAB_PATH, "GHB_F.csv"))
# THYROD_F   = pd.read_csv(os.path.join(LAB_PATH, "THYROD_F.csv"))
VID_F      = pd.read_csv(os.path.join(LAB_PATH, "VID_F.csv"))

# Get columns in the files
DEMO_F = DEMO_F.loc[:, DEMO_F.columns.isin(selected_columns)]
BMX_F = BMX_F.loc[:, BMX_F.columns.isin(selected_columns)]
GLU_F = GLU_F.loc[:, GLU_F.columns.isin(selected_columns)]
BIOPRO_F = BIOPRO_F.loc[:, BIOPRO_F.columns.isin(selected_columns)]
HDL_F = HDL_F.loc[:, HDL_F.columns.isin(selected_columns)]
TRIGLY_F = TRIGLY_F.loc[:, TRIGLY_F.columns.isin(selected_columns)]
CBC_F = CBC_F.loc[:, CBC_F.columns.isin(selected_columns)]
HEPBD_F = HEPBD_F.loc[:, HEPBD_F.columns.isin(selected_columns)]
GHB_F = GHB_F.loc[:, GHB_F.columns.isin(selected_columns)]
# THYROD_F = THYROD_F.loc[:, THYROD_F.columns.isin(selected_columns)]
VID_F = VID_F.loc[:, VID_F.columns.isin(selected_columns)]

# Merge the dataframes
merged_df_F = pd.merge(DEMO_F, BMX_F, on="SEQN", how="inner")
merged_df_F = pd.merge(merged_df_F, GLU_F, on="SEQN", how="inner")
merged_df_F = pd.merge(merged_df_F, BIOPRO_F, on="SEQN", how="inner")
merged_df_F = pd.merge(merged_df_F, HDL_F, on="SEQN", how="inner")
merged_df_F = pd.merge(merged_df_F, TRIGLY_F, on="SEQN", how="inner")
merged_df_F = pd.merge(merged_df_F, CBC_F, on="SEQN", how="inner")
merged_df_F = pd.merge(merged_df_F, HEPBD_F, on="SEQN", how="inner")
merged_df_F = pd.merge(merged_df_F, GHB_F, on="SEQN", how="inner")
# merged_df_F = pd.merge(merged_df_F, THYROD_F, on="SEQN", how="inner")
merged_df_F = pd.merge(merged_df_F, VID_F, on="SEQN", how="inner")
merged_df_F.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3581 entries, 0 to 3580
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      3581 non-null   float64
 1   RIAGENDR  3581 non-null   float64
 2   RIDAGEYR  3581 non-null   float64
 3   RIDRETH1  3581 non-null   float64
 4   BMXBMI    3541 non-null   float64
 5   BMXWAIST  3417 non-null   float64
 6   LBXGLU    3386 non-null   float64
 7   LBDSCHSI  3350 non-null   float64
 8   LBDSTRSI  3347 non-null   float64
 9   LBDSUASI  3349 non-null   float64
 10  LBDHDDSI  3359 non-null   float64
 11  LBDLDLSI  3308 non-null   float64
 12  LBXHGB    3387 non-null   float64
 13  LBXHCT    3387 non-null   float64
 14  LBXMCVSI  3387 non-null   float64
 15  LBXMC     3387 non-null   float64
 16  LBXRDW    3387 non-null   float64
 17  LBXPLTSI  3387 non-null   float64
 18  LBXMPSI   3387 non-null   float64
 19  LBDHBG    3378 non-null   float64
 20  LBXGH     3385 non-null   float64
 21  LBXVIDMS  3379 non-null   float64
dtypes: float64(22)
memory usage: 615.6 KB

# 2011-2012

In [9]:
selected_columns = ["SEQN","RIAGENDR", "RIDAGEYR", "RIDRETH1", "BMXWAIST", "BMXBMI", "LBXGLU", "LBDSUASI", "LBDSCHSI",
"LBDHDDSI","LBDLDLSI","LBDSTRSI","LBXHGB", "LBXHCT","LBXMCVSI","LBXMC","LBXRDW","LBXPLTSI", "LBXMPSI", "LBDHBG", "LBDTSH1S", "LBXVIDMS","LBXGH"]

#file paths
DEMO_PATH = os.path.join(DATA_DIRECTORY, "2011-2012", "Demographics")
LAB_PATH = os.path.join(DATA_DIRECTORY, "2011-2012", "Laboratory")
EXAM_PATH = os.path.join(DATA_DIRECTORY, "2011-2012", "Examination")

# Read in the data
DEMO_G     = pd.read_csv(os.path.join(DEMO_PATH, "DEMO_G.csv"))
BMX_G      = pd.read_csv(os.path.join(EXAM_PATH, "BMX_G.csv"))
GLU_G      = pd.read_csv(os.path.join(LAB_PATH, "GLU_G.csv"))
BIOPRO_G   = pd.read_csv(os.path.join(LAB_PATH, "BIOPRO_G.csv"))
HDL_G      = pd.read_csv(os.path.join(LAB_PATH, "HDL_G.csv"))
TRIGLY_G   = pd.read_csv(os.path.join(LAB_PATH, "TRIGLY_G.csv"))
CBC_G      = pd.read_csv(os.path.join(LAB_PATH, "CBC_G.csv"))
HEPBD_G    = pd.read_csv(os.path.join(LAB_PATH, "HEPBD_G.csv"))
GHB_G     = pd.read_csv(os.path.join(LAB_PATH, "GHB_G.csv"))
# THYROD_G   = pd.read_csv(os.path.join(LAB_PATH, "THYROD_G.csv"))
VID_G      = pd.read_csv(os.path.join(LAB_PATH, "VID_G.csv"))

# Get columns in the files
DEMO_G = DEMO_G.loc[:, DEMO_G.columns.isin(selected_columns)]
BMX_G = BMX_G.loc[:, BMX_G.columns.isin(selected_columns)]
GLU_G = GLU_G.loc[:, GLU_G.columns.isin(selected_columns)]
BIOPRO_G = BIOPRO_G.loc[:, BIOPRO_G.columns.isin(selected_columns)]
HDL_G = HDL_G.loc[:, HDL_G.columns.isin(selected_columns)]
TRIGLY_G = TRIGLY_G.loc[:, TRIGLY_G.columns.isin(selected_columns)]
CBC_G = CBC_G.loc[:, CBC_G.columns.isin(selected_columns)]
HEPBD_G = HEPBD_G.loc[:, HEPBD_G.columns.isin(selected_columns)]
GHB_G = GHB_G.loc[:, GHB_G.columns.isin(selected_columns)]
# THYROD_G = THYROD_G.loc[:, THYROD_G.columns.isin(selected_columns)]
VID_G = VID_G.loc[:, VID_G.columns.isin(selected_columns)]

# Merge the dataframes
merged_df_G = pd.merge(DEMO_G, BMX_G, on="SEQN", how="inner")
merged_df_G = pd.merge(merged_df_G, GLU_G, on="SEQN", how="inner")
merged_df_G = pd.merge(merged_df_G, BIOPRO_G, on="SEQN", how="inner")
merged_df_G = pd.merge(merged_df_G, HDL_G, on="SEQN", how="inner")
merged_df_G = pd.merge(merged_df_G, TRIGLY_G, on="SEQN", how="inner")
merged_df_G = pd.merge(merged_df_G, CBC_G, on="SEQN", how="inner")
merged_df_G = pd.merge(merged_df_G, HEPBD_G, on="SEQN", how="inner")
merged_df_G = pd.merge(merged_df_G, GHB_G, on="SEQN", how="inner")
# merged_df_G = pd.merge(merged_df_G, THYROD_G, on="SEQN", how="inner")
merged_df_G = pd.merge(merged_df_G, VID_G, on="SEQN", how="inner")

merged_df_G.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3239 entries, 0 to 3238
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      3239 non-null   float64
 1   RIAGENDR  3239 non-null   float64
 2   RIDAGEYR  3239 non-null   float64
 3   RIDRETH1  3239 non-null   float64
 4   BMXBMI    3190 non-null   float64
 5   BMXWAIST  3073 non-null   float64
 6   LBXGLU    3033 non-null   float64
 7   LBDSCHSI  2975 non-null   float64
 8   LBDSUASI  2975 non-null   float64
 9   LBDSTRSI  2971 non-null   float64
 10  LBDHDDSI  2992 non-null   float64
 11  LBDLDLSI  2942 non-null   float64
 12  LBXHGB    3069 non-null   float64
 13  LBXHCT    3069 non-null   float64
 14  LBXMCVSI  3069 non-null   float64
 15  LBXMC     3069 non-null   float64
 16  LBXRDW    3069 non-null   float64
 17  LBXPLTSI  3068 non-null   float64
 18  LBXMPSI   3068 non-null   float64
 19  LBDHBG    3014 non-null   float64
 20  LBXGH     3059 non-null   float64
 21  LBXVIDMS  3022 non-null   float64
dtypes: float64(22)
memory usage: 556.8 KB

# 2013-2014

In [10]:
selected_columns = ["SEQN","RIAGENDR", "RIDAGEYR", "RIDRETH1", "BMXWAIST", "BMXBMI", "LBXGLU", "LBDSUASI", "LBDSCHSI",
"LBDHDDSI","LBDLDLSI","LBDSTRSI","LBXHGB", "LBXHCT","LBXMCVSI","LBXMC","LBXRDW","LBXPLTSI", "LBXMPSI", "LBDHBG", "LBDTSH1S", "LBXVIDMS","LBXGH"]

#file paths
DEMO_PATH = os.path.join(DATA_DIRECTORY, "2013-2014", "Demographics")
LAB_PATH = os.path.join(DATA_DIRECTORY, "2013-2014", "Laboratory")
EXAM_PATH = os.path.join(DATA_DIRECTORY, "2013-2014", "Examination")

# Read in the data
DEMO_H     = pd.read_csv(os.path.join(DEMO_PATH, "DEMO_H.csv"))
BMX_H      = pd.read_csv(os.path.join(EXAM_PATH, "BMX_H.csv"))
GLU_H      = pd.read_csv(os.path.join(LAB_PATH, "GLU_H.csv"))
BIOPRO_H   = pd.read_csv(os.path.join(LAB_PATH, "BIOPRO_H.csv"))
HDL_H      = pd.read_csv(os.path.join(LAB_PATH, "HDL_H.csv"))
TRIGLY_H   = pd.read_csv(os.path.join(LAB_PATH, "TRIGLY_H.csv"))
CBC_H      = pd.read_csv(os.path.join(LAB_PATH, "CBC_H.csv"))
HEPBD_H    = pd.read_csv(os.path.join(LAB_PATH, "HEPBD_H.csv"))
GHB_H     = pd.read_csv(os.path.join(LAB_PATH, "GHB_H.csv"))
#THYROD_H   = pd.read_csv(os.path.join(LAB_PATH, "THYROD_H.csv"))
VID_H      = pd.read_csv(os.path.join(LAB_PATH, "VID_H.csv"))

# Get columns in the files
DEMO_H = DEMO_H.loc[:, DEMO_H.columns.isin(selected_columns)]
BMX_H = BMX_H.loc[:, BMX_H.columns.isin(selected_columns)]
GLU_H = GLU_H.loc[:, GLU_H.columns.isin(selected_columns)]
BIOPRO_H = BIOPRO_H.loc[:, BIOPRO_H.columns.isin(selected_columns)]
HDL_H = HDL_H.loc[:, HDL_H.columns.isin(selected_columns)]
TRIGLY_H = TRIGLY_H.loc[:, TRIGLY_H.columns.isin(selected_columns)]
CBC_H = CBC_H.loc[:, CBC_H.columns.isin(selected_columns)]
HEPBD_H = HEPBD_H.loc[:, HEPBD_H.columns.isin(selected_columns)]
GHB_H = GHB_H.loc[:, GHB_H.columns.isin(selected_columns)]
#THYROD_H = THYROD_H.loc[:, THYROD_H.columns.isin(selected_columns)]
VID_H = VID_H.loc[:, VID_H.columns.isin(selected_columns)]

# Merge the dataframes
merged_df_H = pd.merge(DEMO_H, BMX_H, on="SEQN", how="inner")
merged_df_H = pd.merge(merged_df_H, GLU_H, on="SEQN", how="inner")
merged_df_H = pd.merge(merged_df_H, BIOPRO_H, on="SEQN", how="inner")
merged_df_H = pd.merge(merged_df_H, HDL_H, on="SEQN", how="inner")
merged_df_H = pd.merge(merged_df_H, TRIGLY_H, on="SEQN", how="inner")
merged_df_H = pd.merge(merged_df_H, CBC_H, on="SEQN", how="inner")
merged_df_H = pd.merge(merged_df_H, HEPBD_H, on="SEQN", how="inner")
merged_df_H = pd.merge(merged_df_H, GHB_H, on="SEQN", how="inner")
#merged_df_H = pd.merge(merged_df_H, THYROD_H, on="SEQN", how="inner")
merged_df_H = pd.merge(merged_df_H, VID_H, on="SEQN", how="inner")

merged_df_H.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3329 entries, 0 to 3328
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      3329 non-null   float64
 1   RIAGENDR  3329 non-null   float64
 2   RIDAGEYR  3329 non-null   float64
 3   RIDRETH1  3329 non-null   float64
 4   BMXBMI    3291 non-null   float64
 5   BMXWAIST  3160 non-null   float64
 6   LBXGLU    3172 non-null   float64
 7   LBDSCHSI  3134 non-null   float64
 8   LBDSTRSI  3132 non-null   float64
 9   LBDSUASI  3134 non-null   float64
 10  LBDHDDSI  3148 non-null   float64
 11  LBDLDLSI  3105 non-null   float64
 12  LBXHGB    3184 non-null   float64
 13  LBXHCT    3184 non-null   float64
 14  LBXMCVSI  3184 non-null   float64
 15  LBXMC     3184 non-null   float64
 16  LBXRDW    3184 non-null   float64
 17  LBXPLTSI  3184 non-null   float64
 18  LBXMPSI   3184 non-null   float64
 19  LBDHBG    3159 non-null   float64
 20  LBXGH     3184 non-null   float64
 21  LBXVIDMS  3165 non-null   float64
dtypes: float64(22)
memory usage: 572.3 KB

# 2015-2016

In [11]:
selected_columns = ["SEQN","RIAGENDR", "RIDAGEYR", "RIDRETH1", "BMXWAIST", "BMXBMI", "LBXGLU", "LBDSUASI", "LBDSCHSI",
"LBDHDDSI","LBDLDLSI","LBDSTRSI","LBXHGB", "LBXHCT","LBXMCVSI","LBXMC","LBXRDW","LBXPLTSI", "LBXMPSI", "LBDHBG", "LBDTSH1S", "LBXVIDMS","LBXGH"]

#file paths
DEMO_PATH = os.path.join(DATA_DIRECTORY, "2015-2016", "Demographics")
LAB_PATH = os.path.join(DATA_DIRECTORY, "2015-2016", "Laboratory")
EXAM_PATH = os.path.join(DATA_DIRECTORY, "2015-2016", "Examination")

# Read in the data
DEMO_I     = pd.read_csv(os.path.join(DEMO_PATH, "DEMO_I.csv"))
BMX_I      = pd.read_csv(os.path.join(EXAM_PATH, "BMX_I.csv"))
GLU_I      = pd.read_csv(os.path.join(LAB_PATH, "GLU_I.csv"))
BIOPRO_I   = pd.read_csv(os.path.join(LAB_PATH, "BIOPRO_I.csv"))
HDL_I      = pd.read_csv(os.path.join(LAB_PATH, "HDL_I.csv"))
TRIGLY_I   = pd.read_csv(os.path.join(LAB_PATH, "TRIGLY_I.csv"))
CBC_I      = pd.read_csv(os.path.join(LAB_PATH, "CBC_I.csv"))
HEPBD_I    = pd.read_csv(os.path.join(LAB_PATH, "HEPBD_I.csv"))
GHB_I     = pd.read_csv(os.path.join(LAB_PATH, "GHB_I.csv"))
# THYROD_I   = pd.read_csv(os.path.join(LAB_PATH, "THYROD_I.csv"))
VID_I      = pd.read_csv(os.path.join(LAB_PATH, "VID_I.csv"))

# Get columns in the files
DEMO_I = DEMO_I.loc[:, DEMO_I.columns.isin(selected_columns)]
BMX_I = BMX_I.loc[:, BMX_I.columns.isin(selected_columns)]
GLU_I = GLU_I.loc[:, GLU_I.columns.isin(selected_columns)]
BIOPRO_I = BIOPRO_I.loc[:, BIOPRO_I.columns.isin(selected_columns)]
HDL_I = HDL_I.loc[:, HDL_I.columns.isin(selected_columns)]
TRIGLY_I = TRIGLY_I.loc[:, TRIGLY_I.columns.isin(selected_columns)]
CBC_I = CBC_I.loc[:, CBC_I.columns.isin(selected_columns)]
HEPBD_I = HEPBD_I.loc[:, HEPBD_I.columns.isin(selected_columns)]
GHB_I = GHB_I.loc[:, GHB_I.columns.isin(selected_columns)]
# THYROD_I = THYROD_I.loc[:, THYROD_I.columns.isin(selected_columns)]
VID_I = VID_I.loc[:, VID_I.columns.isin(selected_columns)]

# Merge the dataframes
merged_df_I = pd.merge(DEMO_I, BMX_I, on="SEQN", how="inner")
merged_df_I = pd.merge(merged_df_I, GLU_I, on="SEQN", how="inner")
merged_df_I = pd.merge(merged_df_I, BIOPRO_I, on="SEQN", how="inner")
merged_df_I = pd.merge(merged_df_I, HDL_I, on="SEQN", how="inner")
merged_df_I = pd.merge(merged_df_I, TRIGLY_I, on="SEQN", how="inner")
merged_df_I = pd.merge(merged_df_I, CBC_I, on="SEQN", how="inner")
merged_df_I = pd.merge(merged_df_I, HEPBD_I, on="SEQN", how="inner")
merged_df_I = pd.merge(merged_df_I, GHB_I, on="SEQN", how="inner")
# merged_df_I = pd.merge(merged_df_I, THYROD_I, on="SEQN", how="inner")
merged_df_I = pd.merge(merged_df_I, VID_I, on="SEQN", how="inner")
merged_df_I.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3191 entries, 0 to 3190
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      3191 non-null   float64
 1   RIAGENDR  3191 non-null   float64
 2   RIDAGEYR  3191 non-null   float64
 3   RIDRETH1  3191 non-null   float64
 4   BMXBMI    3154 non-null   float64
 5   BMXWAIST  3009 non-null   float64
 6   LBXGLU    2972 non-null   float64
 7   LBDSCHSI  2948 non-null   float64
 8   LBDSTRSI  2948 non-null   float64
 9   LBDSUASI  2948 non-null   float64
 10  LBDHDDSI  2953 non-null   float64
 11  LBDLDLSI  2699 non-null   float64
 12  LBXHGB    2973 non-null   float64
 13  LBXHCT    2973 non-null   float64
 14  LBXMCVSI  2973 non-null   float64
 15  LBXMC     2980 non-null   float64
 16  LBXRDW    2973 non-null   float64
 17  LBXPLTSI  2973 non-null   float64
 18  LBXMPSI   2973 non-null   float64
 19  LBDHBG    182 non-null    float64
 20  LBXGH     2981 non-null   float64
 21  LBXVIDMS  2969 non-null   float64
dtypes: float64(22)
memory usage: 548.6 KB

# 2017-2018

In [12]:
selected_columns = ["SEQN","RIAGENDR", "RIDAGEYR", "RIDRETH1", "BMXWAIST", "BMXBMI", "LBXGLU", "LBDSUASI", "LBDSCHSI",
"LBDHDDSI","LBDLDLSI","LBDSTRSI","LBXHGB", "LBXHCT","LBXMCVSI","LBXMC","LBXRDW","LBXPLTSI", "LBXMPSI", "LBDHBG", "LBDTSH1S", "LBXVIDMS","LBXGH"]

#file paths
DEMO_PATH = os.path.join(DATA_DIRECTORY, "2017-2018", "Demographics")
LAB_PATH = os.path.join(DATA_DIRECTORY, "2017-2018", "Laboratory")
EXAM_PATH = os.path.join(DATA_DIRECTORY, "2017-2018", "Examination")

# Read in the data
DEMO_J     = pd.read_csv(os.path.join(DEMO_PATH, "DEMO_J.csv"))
BMX_J      = pd.read_csv(os.path.join(EXAM_PATH, "BMX_J.csv"))
GLU_J      = pd.read_csv(os.path.join(LAB_PATH, "GLU_J.csv"))
BIOPRO_J   = pd.read_csv(os.path.join(LAB_PATH, "BIOPRO_J.csv"))
HDL_J      = pd.read_csv(os.path.join(LAB_PATH, "HDL_J.csv"))
TRIGLY_J   = pd.read_csv(os.path.join(LAB_PATH, "TRIGLY_J.csv"))
CBC_J      = pd.read_csv(os.path.join(LAB_PATH, "CBC_J.csv"))
HEPBD_J    = pd.read_csv(os.path.join(LAB_PATH, "HEPBD_J.csv"))
GHB_J     = pd.read_csv(os.path.join(LAB_PATH, "GHB_J.csv"))
# THYROD_J   = pd.read_csv(os.path.join(LAB_PATH, "THYROD_J.csv"))
VID_J      = pd.read_csv(os.path.join(LAB_PATH, "VID_J.csv"))

# Get columns in the files
DEMO_J = DEMO_J.loc[:, DEMO_J.columns.isin(selected_columns)]
BMX_J = BMX_J.loc[:, BMX_J.columns.isin(selected_columns)]
GLU_J = GLU_J.loc[:, GLU_J.columns.isin(selected_columns)]
BIOPRO_J = BIOPRO_J.loc[:, BIOPRO_J.columns.isin(selected_columns)]
HDL_J = HDL_J.loc[:, HDL_J.columns.isin(selected_columns)]
TRIGLY_J = TRIGLY_J.loc[:, TRIGLY_J.columns.isin(selected_columns)]
CBC_J = CBC_J.loc[:, CBC_J.columns.isin(selected_columns)]
HEPBD_J = HEPBD_J.loc[:, HEPBD_J.columns.isin(selected_columns)]
GHB_J = GHB_J.loc[:, GHB_J.columns.isin(selected_columns)]
# THYROD_J = THYROD_J.loc[:, THYROD_J.columns.isin(selected_columns)]
VID_J = VID_J.loc[:, VID_J.columns.isin(selected_columns)]

# Merge the dataframes
merged_df_J = pd.merge(DEMO_J, BMX_J, on="SEQN", how="inner")
merged_df_J = pd.merge(merged_df_J, GLU_J, on="SEQN", how="inner")
merged_df_J = pd.merge(merged_df_J, BIOPRO_J, on="SEQN", how="inner")
merged_df_J = pd.merge(merged_df_J, HDL_J, on="SEQN", how="inner")
merged_df_J = pd.merge(merged_df_J, TRIGLY_J, on="SEQN", how="inner")
merged_df_J = pd.merge(merged_df_J, CBC_J, on="SEQN", how="inner")
merged_df_J = pd.merge(merged_df_J, HEPBD_J, on="SEQN", how="inner")
merged_df_J = pd.merge(merged_df_J, GHB_J, on="SEQN", how="inner")
# merged_df_J = pd.merge(merged_df_J, THYROD_J, on="SEQN", how="inner")
merged_df_J = pd.merge(merged_df_J, VID_J, on="SEQN", how="inner")

merged_df_J.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3036 entries, 0 to 3035
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      3036 non-null   float64
 1   RIAGENDR  3036 non-null   float64
 2   RIDAGEYR  3036 non-null   float64
 3   RIDRETH1  3036 non-null   float64
 4   BMXBMI    2981 non-null   float64
 5   BMXWAIST  2869 non-null   float64
 6   LBXGLU    2891 non-null   float64
 7   LBDSCHSI  2832 non-null   float64
 8   LBDSTRSI  2830 non-null   float64
 9   LBDSUASI  2830 non-null   float64
 10  LBDHDDSI  2840 non-null   float64
 11  LBDLDLSI  2808 non-null   float64
 12  LBXHGB    2909 non-null   float64
 13  LBXHCT    2909 non-null   float64
 14  LBXMCVSI  2909 non-null   float64
 15  LBXMC     2909 non-null   float64
 16  LBXRDW    2909 non-null   float64
 17  LBXPLTSI  2909 non-null   float64
 18  LBXMPSI   2909 non-null   float64
 19  LBDHBG    210 non-null    float64
 20  LBXGH     2899 non-null   float64
 21  LBXVIDMS  2875 non-null   float64
dtypes: float64(22)
memory usage: 521.9 KB

# 1. EDA

# 2.INSTRUCTION LIST: RAW->TIDY

## 2.1. Get information of each dataframe

In [13]:
#2001-2002
merged_df_B
#2003-2004
merged_df_C
#2005-2006
merged_df_D
#2007-2008
merged_df_E
#2009-2010
merged_df_F
#2011-2012
merged_df_G
#2013-2014
merged_df_H
#2015-2016
merged_df_I
#2017-2018
merged_df_J

,SEQN,RIAGENDR,RIDAGEYR,RIDRETH1,BMXBMI,BMXWAIST,LBXGLU,LBDSCHSI,LBDSTRSI,LBDSUASI,...,LBXHGB,LBXHCT,LBXMCVSI,LBXMC,LBXRDW,LBXPLTSI,LBXMPSI,LBDHBG,LBXGH,LBXVIDMS
0,93708.0,2.0,66.0,5.0,23.7,88.2,122.0,5.431,0.813,267.7,...,13.2,39.9,86.8,33.1,13.4,226.0,9.1,2.0,6.2,116.0
1,93711.0,1.0,56.0,5.0,21.3,86.6,107.0,6.181,0.666,249.8,...,14.7,43.2,92.9,34.1,13.3,264.0,7.7,NaN,5.7,165.0
2,93717.0,1.0,22.0,3.0,24.5,86.2,91.0,5.612,1.377,392.6,...,14.4,43.8,91.1,32.9,13.1,238.0,8.8,NaN,5.1,54.2
3,93718.0,1.0,45.0,4.0,22.0,77.5,89.0,3.931,0.644,267.7,...,14.6,43.0,91.3,33.8,13.1,272.0,7.5,NaN,5.7,76.4
4,93719.0,2.0,13.0,3.0,26.0,86.0,86.0,2.457,1.073,315.2,...,14.6,43.7,93.8,33.4,12.6,283.0,7.3,NaN,5.0,77.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3031,102947.0,1.0,75.0,4.0,25.2,94.0,85.0,3.672,0.497,404.5,...,10.7,34.8,70.6,30.7,20.0,118.0,9.3,NaN,5.8,216.0
3032,102948.0,2.0,31.0,3.0,20.2,69.7,92.0,5.301,0.711,237.9,...,13.4,38.6,91.5,34.7,12.7,221.0,8.7,NaN,5.2,76.7
3033,102952.0,2.0,70.0,5.0,20.0,82.2,158.0,3.129,1.106,380.7,...,13.4,40.6,87.7,33.1,13.3,161.0,9.1,2.0,7.4,82.7
3034,102954.0,2.0,41.0,4.0,26.1,86.4,94.0,4.448,0.723,184.4,...,6.4,23.1,61.9,27.9,19.6,145.0,9.7,NaN,5.2,50.5
3035,102956.0,1.0,38.0,3.0,36.1,122.0,91.0,4.319,3.263,380.7,...,17.4,50.1,91.8,34.7,13.3,159.0,8.5,NaN,5.4,58.9

In [14]:
merged_df_B.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3666 entries, 0 to 3665
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      3666 non-null   float64
 1   RIAGENDR  3666 non-null   float64
 2   RIDAGEYR  3666 non-null   float64
 3   RIDRETH1  3666 non-null   float64
 4   BMXBMI    3493 non-null   float64
 5   BMXWAIST  3515 non-null   float64
 6   LBXGLU    3441 non-null   float64
 7   LBXGLUSI  3441 non-null   float64
 8   LBDSCHSI  3392 non-null   float64
 9   LBDHDLSI  3382 non-null   float64
 10  LBDTRSI   3382 non-null   float64
 11  LBDLDLSI  3038 non-null   float64
 12  LBXHGB    3460 non-null   float64
 13  LBXHCT    3460 non-null   float64
 14  LBXMCVSI  3460 non-null   float64
 15  LBXMC     3460 non-null   float64
 16  LBXRDW    3460 non-null   float64
 17  LBXPLTSI  3460 non-null   float64
 18  LBXMPSI   3460 non-null   float64
 19  LBDHBG    3418 non-null   float64
 20  LBXGH     3457 non-null   float64
 21  LBDVIDMS  3344 non-null   float64
dtypes: float64(22)
memory usage: 630.2 KB

In [15]:
merged_df_C.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3356 entries, 0 to 3355
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      3356 non-null   float64
 1   RIAGENDR  3356 non-null   float64
 2   RIDAGEYR  3356 non-null   float64
 3   RIDRETH1  3356 non-null   float64
 4   BMXBMI    3308 non-null   float64
 5   BMXWAIST  3205 non-null   float64
 6   LBXGLU    3169 non-null   float64
 7   LBDSCHSI  3138 non-null   float64
 8   LBDSUASI  3138 non-null   float64
 9   LBDHDDSI  3148 non-null   float64
 10  LBDTRSI   3141 non-null   float64
 11  LBDLDLSI  3079 non-null   float64
 12  LBXHGB    3199 non-null   float64
 13  LBXHCT    3199 non-null   float64
 14  LBXMCVSI  3199 non-null   float64
 15  LBXMC     3199 non-null   float64
 16  LBXRDW    3199 non-null   float64
 17  LBXPLTSI  3199 non-null   float64
 18  LBXMPSI   3199 non-null   float64
 19  LBDHBG    3159 non-null   float64
 20  LBXGH     3191 non-null   float64
 21  LBDVIDMS  3165 non-null   float64
dtypes: float64(22)
memory usage: 576.9 KB

In [16]:
#2005-2006
merged_df_D.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3352 entries, 0 to 3351
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      3352 non-null   float64
 1   RIAGENDR  3352 non-null   float64
 2   RIDAGEYR  3352 non-null   float64
 3   RIDRETH1  3352 non-null   float64
 4   BMXBMI    3302 non-null   float64
 5   BMXWAIST  3216 non-null   float64
 6   LBXGLU    3128 non-null   float64
 7   LBDSCHSI  3094 non-null   float64
 8   LBDSTRSI  3093 non-null   float64
 9   LBDSUASI  3095 non-null   float64
 10  LBDHDDSI  3106 non-null   float64
 11  LBDLDLSI  3026 non-null   float64
 12  LBXHGB    3137 non-null   float64
 13  LBXHCT    3137 non-null   float64
 14  LBXMCVSI  3137 non-null   float64
 15  LBXMC     3137 non-null   float64
 16  LBXRDW    3137 non-null   float64
 17  LBXPLTSI  3137 non-null   float64
 18  LBXMPSI   3137 non-null   float64
 19  LBDHBG    3119 non-null   float64
 20  LBXGH     3131 non-null   float64
 21  LBDVIDMS  3121 non-null   float64
dtypes: float64(22)
memory usage: 576.3 KB

In [17]:
merged_df_E.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3315 entries, 0 to 3314
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      3315 non-null   float64
 1   RIAGENDR  3315 non-null   float64
 2   RIDAGEYR  3315 non-null   float64
 3   RIDRETH1  3315 non-null   float64
 4   BMXBMI    3251 non-null   float64
 5   BMXWAIST  3136 non-null   float64
 6   LBXGLU    3110 non-null   float64
 7   LBDSCHSI  3085 non-null   float64
 8   LBDSTRSI  3085 non-null   float64
 9   LBDSUASI  3085 non-null   float64
 10  LBDHDDSI  3102 non-null   float64
 11  LBDLDLSI  3035 non-null   float64
 12  LBXHGB    3112 non-null   float64
 13  LBXHCT    3112 non-null   float64
 14  LBXMCVSI  3112 non-null   float64
 15  LBXMC     3112 non-null   float64
 16  LBXRDW    3112 non-null   float64
 17  LBXPLTSI  3112 non-null   float64
 18  LBXMPSI   3112 non-null   float64
 19  LBDHBG    3111 non-null   float64
 20  LBXGH     3110 non-null   float64
 21  LBXVIDMS  2682 non-null   float64
dtypes: float64(22)
memory usage: 569.9 KB

In [18]:
merged_df_H.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3329 entries, 0 to 3328
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      3329 non-null   float64
 1   RIAGENDR  3329 non-null   float64
 2   RIDAGEYR  3329 non-null   float64
 3   RIDRETH1  3329 non-null   float64
 4   BMXBMI    3291 non-null   float64
 5   BMXWAIST  3160 non-null   float64
 6   LBXGLU    3172 non-null   float64
 7   LBDSCHSI  3134 non-null   float64
 8   LBDSTRSI  3132 non-null   float64
 9   LBDSUASI  3134 non-null   float64
 10  LBDHDDSI  3148 non-null   float64
 11  LBDLDLSI  3105 non-null   float64
 12  LBXHGB    3184 non-null   float64
 13  LBXHCT    3184 non-null   float64
 14  LBXMCVSI  3184 non-null   float64
 15  LBXMC     3184 non-null   float64
 16  LBXRDW    3184 non-null   float64
 17  LBXPLTSI  3184 non-null   float64
 18  LBXMPSI   3184 non-null   float64
 19  LBDHBG    3159 non-null   float64
 20  LBXGH     3184 non-null   float64
 21  LBXVIDMS  3165 non-null   float64
dtypes: float64(22)
memory usage: 572.3 KB

In [19]:
merged_df_I.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3191 entries, 0 to 3190
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      3191 non-null   float64
 1   RIAGENDR  3191 non-null   float64
 2   RIDAGEYR  3191 non-null   float64
 3   RIDRETH1  3191 non-null   float64
 4   BMXBMI    3154 non-null   float64
 5   BMXWAIST  3009 non-null   float64
 6   LBXGLU    2972 non-null   float64
 7   LBDSCHSI  2948 non-null   float64
 8   LBDSTRSI  2948 non-null   float64
 9   LBDSUASI  2948 non-null   float64
 10  LBDHDDSI  2953 non-null   float64
 11  LBDLDLSI  2699 non-null   float64
 12  LBXHGB    2973 non-null   float64
 13  LBXHCT    2973 non-null   float64
 14  LBXMCVSI  2973 non-null   float64
 15  LBXMC     2980 non-null   float64
 16  LBXRDW    2973 non-null   float64
 17  LBXPLTSI  2973 non-null   float64
 18  LBXMPSI   2973 non-null   float64
 19  LBDHBG    182 non-null    float64
 20  LBXGH     2981 non-null   float64
 21  LBXVIDMS  2969 non-null   float64
dtypes: float64(22)
memory usage: 548.6 KB

In [20]:
merged_df_J.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3036 entries, 0 to 3035
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      3036 non-null   float64
 1   RIAGENDR  3036 non-null   float64
 2   RIDAGEYR  3036 non-null   float64
 3   RIDRETH1  3036 non-null   float64
 4   BMXBMI    2981 non-null   float64
 5   BMXWAIST  2869 non-null   float64
 6   LBXGLU    2891 non-null   float64
 7   LBDSCHSI  2832 non-null   float64
 8   LBDSTRSI  2830 non-null   float64
 9   LBDSUASI  2830 non-null   float64
 10  LBDHDDSI  2840 non-null   float64
 11  LBDLDLSI  2808 non-null   float64
 12  LBXHGB    2909 non-null   float64
 13  LBXHCT    2909 non-null   float64
 14  LBXMCVSI  2909 non-null   float64
 15  LBXMC     2909 non-null   float64
 16  LBXRDW    2909 non-null   float64
 17  LBXPLTSI  2909 non-null   float64
 18  LBXMPSI   2909 non-null   float64
 19  LBDHBG    210 non-null    float64
 20  LBXGH     2899 non-null   float64
 21  LBXVIDMS  2875 non-null   float64
dtypes: float64(22)
memory usage: 521.9 KB

## 2. Rename column

In [21]:
#rename for 2001->2004
def rename_nhanes_columns_2001_2004(df):
    rename_map = {
        "SEQN": "SEQN",
        "RIAGENDR":"Gender",
        "LBXGH":"Hba1c",
        "RIDAGEYR": "Age",
        "RIDRETH1": "Race",
        "BMXBMI": "BMI",
        "BMXWAIST": "WaistCircumference",
        "LBXGLU": "FastingGlucose", 
        "LBXGLUSI": "UricAcid",
        "LBDSCHSI":"TotalCholesterol",
        "LBDHDDSI": "HDLCholesterol",
        "LBDHDLSI": "HDLCholesterol",
        "LBDLDLSI": "LDLCholesterol",
        "LBDTRSI": "Triglycerides",
        "LBDHBG":"HBsAg",
        "LBXHGB": "Hemoglobin",
        "LBXHCT": "Hematocrit",
        "LBDSUASI": "UricAcid",
        "LBXMCVSI": "MeanCellVolumn",
        "LBXMC": "MeanCellHemoglobin",
        "LBXRDW": "RedCellDistributionWidth",
        "LBXPLTSI": "PlateletCount",
        "LBXMPSI": "MeanPlateletVolume",
        "LBXTSH": "HBsAg",
        "LBDVIDMS": "VitaminD"
    }
    return df.rename(columns=rename_map)

In [22]:
def rename_nhanes_columns(df):
    rename_map = {
        "SEQN": "SEQN",
        "RIAGENDR":"Gender",
        "LBXGH":"Hba1c",
        "RIDAGEYR": "Age",
        "RIDRETH1": "Race",
        "BMXBMI": "BMI",
        "BMXWAIST": "WaistCircumference",
        "LBXGLU": "FastingGlucose",
        "LBDSCHSI": "TotalCholesterol",
        "LBDSUASI": "UricAcid",
        "LBDLDLSI": "LDLCholesterol",
        "LBDHDDSI": "HDLCholesterol",
        "LBDHDLSI": "HDLCholesterol",
        "LBDSTRSI": "Triglycerides",
        "LBDHBG":"HBsAg",
        "LBXHGB": "Hemoglobin",
        "LBXHCT": "Hematocrit",
        "LBXMCVSI": "MeanCellVolumn",
        "LBXMC": "MeanCellHemoglobin",
        "LBXRDW": "RedCellDistributionWidth",
        "LBXPLTSI": "PlateletCount",
        "LBXMPSI": "MeanPlateletVolume",
        "LBXTSH": "Thyroid Stimulating Hormone",
        "LBXVIDMS": "VitaminD",
        "LBDVIDMS":"VitaminD"
    }
    return df.rename(columns=rename_map)

In [23]:
selected_columns = ["SEQN","RIAGENDR", "RIDAGEYR", "RIDRETH1", "BMXWAIST", "BMXBMI", "LBXGLU", "LBDSUASI", "LBDSCHSI",
"LBDHDDSI","LBDLDLSI","LBDSTRSI","LBXHGB", "LBXHCT","LBXMCVSI","LBXMC","LBXRDW","LBXPLTSI", "LBXMPSI", "LBDHBG", "LBDTSH1S", "LBXVIDMS","LBXGH"]

#file paths
DEMO_PATH = os.path.join(DATA_DIRECTORY, "2007-2008", "Demographics")
LAB_PATH = os.path.join(DATA_DIRECTORY, "2007-2008", "Laboratory")
EXAM_PATH = os.path.join(DATA_DIRECTORY, "2007-2008", "Examination")

#read in the data
DEMO_E     = pd.read_csv(os.path.join(DEMO_PATH, "DEMO_E.csv"))
BMX_E      = pd.read_csv(os.path.join(EXAM_PATH, "BMX_E.csv"))
GLU_E      = pd.read_csv(os.path.join(LAB_PATH, "GLU_E.csv"))
BIOPRO_E   = pd.read_csv(os.path.join(LAB_PATH, "BIOPRO_E.csv"))
HDL_E      = pd.read_csv(os.path.join(LAB_PATH, "HDL_E.csv"))
TRIGLY_E   = pd.read_csv(os.path.join(LAB_PATH, "TRIGLY_E.csv"))
CBC_E      = pd.read_csv(os.path.join(LAB_PATH, "CBC_E.csv"))
HEPBD_E    = pd.read_csv(os.path.join(LAB_PATH, "HEPBD_E.csv"))
GHB_E     = pd.read_csv(os.path.join(LAB_PATH, "GHB_E.csv"))
# THYROD_E   = pd.read_csv(os.path.join(LAB_PATH, "THYROD_E.csv"))
VID_E      = pd.read_csv(os.path.join(LAB_PATH, "VID_E.csv"))

#get columns in the files
DEMO_E = DEMO_E.loc[:, DEMO_E.columns.isin(selected_columns)]
BMX_E = BMX_E.loc[:, BMX_E.columns.isin(selected_columns)]
GLU_E = GLU_E.loc[:, GLU_E.columns.isin(selected_columns)]
BIOPRO_E = BIOPRO_E.loc[:, BIOPRO_E.columns.isin(selected_columns)]
HDL_E = HDL_E.loc[:, HDL_E.columns.isin(selected_columns)]
TRIGLY_E = TRIGLY_E.loc[:, TRIGLY_E.columns.isin(selected_columns)]
CBC_E = CBC_E.loc[:, CBC_E.columns.isin(selected_columns)]
HEPBD_E = HEPBD_E.loc[:, HEPBD_E.columns.isin(selected_columns)]
# THYROD_E = THYROD_E.loc[:, THYROD_E.columns.isin(selected_columns)]
GHB_E = GHB_E.loc[:, GHB_E.columns.isin(selected_columns)]
VID_E = VID_E.loc[:, VID_E.columns.isin(selected_columns)]

#merge the dataframes
merged_df_E = pd.merge(DEMO_E, BMX_E, on="SEQN", how="inner")
merged_df_E = pd.merge(merged_df_E, GLU_E, on="SEQN", how="inner")
merged_df_E = pd.merge(merged_df_E, BIOPRO_E, on="SEQN", how="inner")
merged_df_E = pd.merge(merged_df_E, HDL_E, on="SEQN", how="inner")
merged_df_E = pd.merge(merged_df_E, TRIGLY_E, on="SEQN", how="inner")
merged_df_E = pd.merge(merged_df_E, CBC_E, on="SEQN", how="inner")
merged_df_E = pd.merge(merged_df_E, HEPBD_E, on="SEQN", how="inner")
merged_df_E = pd.merge(merged_df_E, GHB_E, on="SEQN", how="inner")
# merged_df_E = pd.merge(merged_df, THYROD_E, on="SEQN", how="inner")
merged_df_E = pd.merge(merged_df_E, VID_E, on="SEQN", how="inner")
merged_df_E.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3315 entries, 0 to 3314
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      3315 non-null   float64
 1   RIAGENDR  3315 non-null   float64
 2   RIDAGEYR  3315 non-null   float64
 3   RIDRETH1  3315 non-null   float64
 4   BMXBMI    3251 non-null   float64
 5   BMXWAIST  3136 non-null   float64
 6   LBXGLU    3110 non-null   float64
 7   LBDSCHSI  3085 non-null   float64
 8   LBDSTRSI  3085 non-null   float64
 9   LBDSUASI  3085 non-null   float64
 10  LBDHDDSI  3102 non-null   float64
 11  LBDLDLSI  3035 non-null   float64
 12  LBXHGB    3112 non-null   float64
 13  LBXHCT    3112 non-null   float64
 14  LBXMCVSI  3112 non-null   float64
 15  LBXMC     3112 non-null   float64
 16  LBXRDW    3112 non-null   float64
 17  LBXPLTSI  3112 non-null   float64
 18  LBXMPSI   3112 non-null   float64
 19  LBDHBG    3111 non-null   float64
 20  LBXGH     3110 non-null   float64
 21  LBXVIDMS  2682 non-null   float64
dtypes: float64(22)
memory usage: 569.9 KB

In [24]:
#from 2005->2018
merged_df_B = rename_nhanes_columns_2001_2004(merged_df_B)
merged_df_C = rename_nhanes_columns_2001_2004(merged_df_C)
merged_df_D = rename_nhanes_columns(merged_df_D)
merged_df_E = rename_nhanes_columns(merged_df_E)
merged_df_F = rename_nhanes_columns(merged_df_F)
merged_df_G = rename_nhanes_columns(merged_df_G)
merged_df_H = rename_nhanes_columns(merged_df_H)
merged_df_I = rename_nhanes_columns(merged_df_I)
merged_df_J = rename_nhanes_columns(merged_df_J)

In [25]:
merged_df_B['YearID'] = '2001-2002'
merged_df_C['YearID'] = '2003-2004'
merged_df_D['YearID'] = '2005-2006'
merged_df_E['YearID'] = '2007-2008'
merged_df_F['YearID'] = '2009-2010'
merged_df_G['YearID'] = '2011-2012'
merged_df_H['YearID'] = '2013-2014'
merged_df_I['YearID'] = '2015-2016'
merged_df_J['YearID'] = '2017-2018'

In [26]:
import pandas as pd

merged_df_all = pd.concat([
    merged_df_B,
    merged_df_C,
    merged_df_D,
    merged_df_E,
    merged_df_F,
    merged_df_G,
    merged_df_H,
    merged_df_I,
    merged_df_J
], ignore_index=True)

In [27]:
merged_df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30065 entries, 0 to 30064
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   SEQN                      30065 non-null  float64
 1   Gender                    30065 non-null  float64
 2   Age                       30065 non-null  float64
 3   Race                      30065 non-null  float64
 4   BMI                       29511 non-null  float64
 5   WaistCircumference        28600 non-null  float64
 6   FastingGlucose            28302 non-null  float64
 7   UricAcid                  27995 non-null  float64
 8   TotalCholesterol          27948 non-null  float64
 9   HDLCholesterol            28030 non-null  float64
 10  Triglycerides             27929 non-null  float64
 11  LDLCholesterol            27040 non-null  float64
 12  Hemoglobin                28430 non-null  float64
 13  Hematocrit                28430 non-null  float64
 14  MeanCellVolumn            28430 non-null  float64
 15  MeanCellHemoglobin        28437 non-null  float64
 16  RedCellDistributionWidth  28430 non-null  float64
 17  PlateletCount             28429 non-null  float64
 18  MeanPlateletVolume        28429 non-null  float64
 19  HBsAg                     22750 non-null  float64
 20  Hba1c                     28397 non-null  float64
 21  VitaminD                  27722 non-null  float64
 22  YearID                    30065 non-null  object
dtypes: float64(22), object(1)
memory usage: 5.3+ MB

In [28]:
merged_df_all.iloc[:,:10].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30065 entries, 0 to 30064
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   SEQN                30065 non-null  float64
 1   Gender              30065 non-null  float64
 2   Age                 30065 non-null  float64
 3   Race                30065 non-null  float64
 4   BMI                 29511 non-null  float64
 5   WaistCircumference  28600 non-null  float64
 6   FastingGlucose      28302 non-null  float64
 7   UricAcid            27995 non-null  float64
 8   TotalCholesterol    27948 non-null  float64
 9   HDLCholesterol      28030 non-null  float64
dtypes: float64(10)
memory usage: 2.3 MB

In [29]:
merged_df_all.iloc[:,10:].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30065 entries, 0 to 30064
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Triglycerides             27929 non-null  float64
 1   LDLCholesterol            27040 non-null  float64
 2   Hemoglobin                28430 non-null  float64
 3   Hematocrit                28430 non-null  float64
 4   MeanCellVolumn            28430 non-null  float64
 5   MeanCellHemoglobin        28437 non-null  float64
 6   RedCellDistributionWidth  28430 non-null  float64
 7   PlateletCount             28429 non-null  float64
 8   MeanPlateletVolume        28429 non-null  float64
 9   HBsAg                     22750 non-null  float64
 10  Hba1c                     28397 non-null  float64
 11  VitaminD                  27722 non-null  float64
 12  YearID                    30065 non-null  object
dtypes: float64(12), object(1)
memory usage: 3.0+ MB

In [30]:
merged_df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30065 entries, 0 to 30064
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   SEQN                      30065 non-null  float64
 1   Gender                    30065 non-null  float64
 2   Age                       30065 non-null  float64
 3   Race                      30065 non-null  float64
 4   BMI                       29511 non-null  float64
 5   WaistCircumference        28600 non-null  float64
 6   FastingGlucose            28302 non-null  float64
 7   UricAcid                  27995 non-null  float64
 8   TotalCholesterol          27948 non-null  float64
 9   HDLCholesterol            28030 non-null  float64
 10  Triglycerides             27929 non-null  float64
 11  LDLCholesterol            27040 non-null  float64
 12  Hemoglobin                28430 non-null  float64
 13  Hematocrit                28430 non-null  float64
 14  MeanCellVolumn            28430 non-null  float64
 15  MeanCellHemoglobin        28437 non-null  float64
 16  RedCellDistributionWidth  28430 non-null  float64
 17  PlateletCount             28429 non-null  float64
 18  MeanPlateletVolume        28429 non-null  float64
 19  HBsAg                     22750 non-null  float64
 20  Hba1c                     28397 non-null  float64
 21  VitaminD                  27722 non-null  float64
 22  YearID                    30065 non-null  object
dtypes: float64(22), object(1)
memory usage: 5.3+ MB

In [31]:
merged_df_all.to_csv(os.path.join("/home/teamq-g2-no2/DiabeteDatachain/src/LMM_DATASET_VITAMINd.csv"), index=False)

In [32]:
merged_df_J.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3036 entries, 0 to 3035
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   SEQN                      3036 non-null   float64
 1   Gender                    3036 non-null   float64
 2   Age                       3036 non-null   float64
 3   Race                      3036 non-null   float64
 4   BMI                       2981 non-null   float64
 5   WaistCircumference        2869 non-null   float64
 6   FastingGlucose            2891 non-null   float64
 7   TotalCholesterol          2832 non-null   float64
 8   Triglycerides             2830 non-null   float64
 9   UricAcid                  2830 non-null   float64
 10  HDLCholesterol            2840 non-null   float64
 11  LDLCholesterol            2808 non-null   float64
 12  Hemoglobin                2909 non-null   float64
 13  Hematocrit                2909 non-null   float64
 14  MeanCellVolumn            2909 non-null   float64
 15  MeanCellHemoglobin        2909 non-null   float64
 16  RedCellDistributionWidth  2909 non-null   float64
 17  PlateletCount             2909 non-null   float64
 18  MeanPlateletVolume        2909 non-null   float64
 19  HBsAg                     210 non-null    float64
 20  Hba1c                     2899 non-null   float64
 21  VitaminD                  2875 non-null   float64
 22  YearID                    3036 non-null   object
dtypes: float64(22), object(1)
memory usage: 545.7+ KB